// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for security
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ofadafpyteysvafyqdqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mYWRhZnB5dGV5c3ZhZnlxZHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDExNDgsImV4cCI6MjA2MzQ3NzE0OH0.OgDtIE9XnjtYRXdaJExpe0X9AA4ew9XGkwZeX6AEUxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
