name: Deploy to Staging

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          echo "VITE_APP_URL=${{ secrets.APP_URL }}" >> .env
          echo "VITE_APP_NAME=${{ secrets.APP_NAME }}" >> .env

      - name: Build main site and CMS
        run: npm run build:all
        
      # Add a file to track deployment
      - name: Create deployment marker file
        run: |
          echo "Deployment timestamp: $(date)" > ./dist/deployment-marker.txt
          echo "GitHub Run ID: ${{ github.run_id }}" >> ./dist/deployment-marker.txt
          echo "Deployed branch: ${{ github.ref_name }}" >> ./dist/deployment-marker.txt
          
          echo "Deployment timestamp: $(date)" > ./dist-cms/deployment-marker.txt
          echo "GitHub Run ID: ${{ github.run_id }}" >> ./dist-cms/deployment-marker.txt
          echo "Deployed branch: ${{ github.ref_name }}" >> ./dist-cms/deployment-marker.txt
          
          # List files for debugging
          echo "Files in dist directory:"
          ls -la ./dist/
          echo "Files in dist/assets directory:"
          ls -la ./dist/assets/
        
      # Enhanced debug info for FTP paths
      - name: Validate FTP path format
        run: |
          echo "Checking FTP path formats..."
          
          # Check if paths start with /
          if [[ ! "$FTP_STAGING_DIR" == /* ]]; then
            echo "WARNING: FTP_STAGING_DIR should start with a forward slash (/)"
          fi
          
          if [[ ! "$FTP_CMS_STAGING_DIR" == /* ]]; then
            echo "WARNING: FTP_CMS_STAGING_DIR should start with a forward slash (/)"
          fi
          
          # Check if paths end with /
          if [[ ! "$FTP_STAGING_DIR" == */ ]]; then
            echo "WARNING: FTP_STAGING_DIR should end with a forward slash (/)"
          fi
          
          if [[ ! "$FTP_CMS_STAGING_DIR" == */ ]]; then
            echo "WARNING: FTP_CMS_STAGING_DIR should end with a forward slash (/)"
          fi
          
          # Check if public_html is included
          if [[ ! "$FTP_STAGING_DIR" == *public_html* ]]; then
            echo "NOTE: FTP_STAGING_DIR may need to include 'public_html' for most hosting providers"
          fi
          
          if [[ ! "$FTP_CMS_STAGING_DIR" == *public_html* ]]; then
            echo "NOTE: FTP_CMS_STAGING_DIR may need to include 'public_html' for most hosting providers"
          fi
          
          echo "FTP_STAGING_DIR first character: ${FTP_STAGING_DIR:0:1}"
          echo "FTP_STAGING_DIR last character: ${FTP_STAGING_DIR: -1}"
          echo "FTP_CMS_STAGING_DIR first character: ${FTP_CMS_STAGING_DIR:0:1}"
          echo "FTP_CMS_STAGING_DIR last character: ${FTP_CMS_STAGING_DIR: -1}"
          
          echo "Path format check complete."
        env:
          FTP_STAGING_DIR: ${{ secrets.FTP_STAGING_DIR }}
          FTP_CMS_STAGING_DIR: ${{ secrets.FTP_CMS_STAGING_DIR }}
        
      - name: Validate FTP Configuration
        id: validate-sftp
        run: |
          if [ -z "$FTP_SERVER" ] || [ -z "$FTP_USERNAME" ] || [ -z "$FTP_PASSWORD" ]; then
            echo "::warning::Missing FTP configuration. Skipping deployment."
            echo "skip_deployment=true" >> $GITHUB_OUTPUT
          else
            echo "FTP configuration is valid."
            echo "skip_deployment=false" >> $GITHUB_OUTPUT
          fi
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

      - name: Deploy main site to Hostinger via FTP (Staging)
        if: steps.validate-sftp.outputs.skip_deployment != 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ secrets.FTP_STAGING_DIR }}
          dangerous-clean-slate: true
          
      - name: Deploy CMS to Hostinger via FTP (Staging)
        if: steps.validate-sftp.outputs.skip_deployment != 'true'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist-cms/
          server-dir: ${{ secrets.FTP_CMS_STAGING_DIR }}
          dangerous-clean-slate: true
          
      - name: Notify on success
        if: success() && env.SLACK_WEBHOOK_URL != ''
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "✅ Staging deployment successful! Sites are live at ${{ secrets.STAGING_URL }} and ${{ secrets.CMS_STAGING_URL }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL || '' }}
          
      - name: Notify on failure
        if: failure() && env.SLACK_WEBHOOK_URL != ''
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "❌ Staging deployment failed! Check the logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL || '' }} 